# Generated by Django 4.1.1 on 2022-09-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_principal', models.PositiveIntegerField(verbose_name='투자 원금')),
                ('quantity', models.PositiveIntegerField(verbose_name='투자 수량')),
                ('investment_time', models.DateTimeField(auto_now_add=True, verbose_name='투자한 날짜')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_account_number', to='accounts.account')),
                ('investment_stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_investment_stock', to='stocks.stock')),
            ],
            options={
                'verbose_name': '투자',
                'verbose_name_plural': '투자 목록',
                'db_table': 'investment',
            },
        ),
    ]
