# Generated by Django 4.1.1 on 2022-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_principal',
            field=models.PositiveBigIntegerField(verbose_name='투자 원금'),
        ),
    ]
