# Generated by Django 4.1.1 on 2022-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_total_investment_principal',
            field=models.PositiveBigIntegerField(verbose_name='계좌별 투자 원금'),
        ),
    ]
