# Generated by Django 4.1.1 on 2022-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=40)),
                ('transfer_amount', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
