# Generated by Django 4.1.1 on 2022-09-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_total_investment_principal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
