# Generated by Django 4.1.1 on 2022-09-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=40)),
                ('transfer_amount', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '투자금 입금',
                'verbose_name_plural': '투자금 입금 목록',
                'db_table': 'transfer',
            },
        ),
    ]
